<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Profile;
use App\Models\Role;
use Illuminate\Support\Facades\Hash;
class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $adminUser = User::create([
            "username" => "admin",
            "password" => Hash::make("password123"),
            "is_admin" => true
        ]);

        $adminUser->profile()->save(
            new Profile([
                "first_name" => "Jomar",
                "last_name" => "Ramos",
                "middle_name" => "Franco",
                "user_id" => $adminUser->id,
                "is_sync" => true
            ])
        );

        $data = '{
            "json_file": [{"branch_id": 1,
                "fullname": {"first_name": "Rae",       
                             "last_name": "Beltran",    
                             "middle_name": "Cabiling"},
                "is_manager": "1",
                "password": "rjb123",
                "username": "rae.joshua"},
               {"branch_id": 1,
                "fullname": {"first_name": "Kelly",     
                             "last_name": "Changco",    
                             "middle_name": "Leonel"},  
                "is_server": "1",
                "password": "kelly123",
                "username": "kelly.leonel"},
               {"branch_id": 1,
                "fullname": {"first_name": "Rosito",
                             "last_name": "Talavera",
                             "middle_name": "John"},
                "is_it": "1",
                "password": "rosito123",
                "username": "rosito.john"},
               {"branch_id": 1,
                "fullname": {"first_name": "Mark",
                             "last_name": "Herras",
                             "middle_name": "Quin"},
                "password": "mark123",
                "username": "mark.her"},
               {"branch_id": 1,
                "fullname": {"first_name": "Daniel",
                             "last_name": "Padilla",
                             "middle_name": "Ford"},
                "password": "djp123",
                "username": "daniel.p"},
               {"branch_id": 1,
                "fullname": {"first_name": "Christian",
                             "last_name": "Reyes",
                             "middle_name": "Mello"},
                "password": "cmr123",
                "username": "chris.td"},
               {"branch_id": 1,
                "fullname": {"first_name": "Rolan",
                             "last_name": "Canco",
                             "middle_name": "Jean"},
                "password": "rjc123",
                "username": "rolan.j"},
               {"branch_id": 1,
                "fullname": {"first_name": "Keith",
                             "last_name": "Markos",
                             "middle_name": "Diego"},
                "password": "kdm123",
                "username": "keith.mark"},
               {"branch_id": 2,
                "fullname": {"first_name": "Keiko",
                             "last_name": "Suva",
                             "middle_name": "Trinidad"},
                "is_manager": "1",
                "password": "kts123",
                "username": "keiko.suva"},
               {"branch_id": 2,
                "fullname": {"first_name": "Samuel",
                             "last_name": "Lugtu",
                             "middle_name": "Trinidad"},
                "is_server": "1",
                "password": "stl123",
                "username": "sam.lugtu"},
               {"branch_id": 2,
                "fullname": {"first_name": "Gabriel",
                             "last_name": "Guibao",
                             "middle_name": "Trinidad"},
                "is_it": "1",
                "password": "gsl123",
                "username": "gsl.trd"},
               {"branch_id": 2,
                "fullname": {"first_name": "John",
                             "last_name": "James",
                             "middle_name": "Beltran"},
                "password": "jbj123",
                "username": "john.james"},
               {"branch_id": 2,
                "fullname": {"first_name": "Kobe",
                             "last_name": "Luke",
                             "middle_name": "Paras"},
                "password": "kbl123",
                "username": "kobe.luke"},
               {"branch_id": 2,
                "fullname": {"first_name": "Saira",
                             "last_name": "Lampano",
                             "middle_name": "Ramos"},
                "password": "srl",
                "username": "sai.lampano"},
               {"branch_id": 2,
                "fullname": {"first_name": "Rovic",
                             "last_name": "Gagno",
                             "middle_name": "Mark"},
                "password": "rmg123",
                "username": "rovic.gagno"},
               {"branch_id": 2,
                "fullname": {"first_name": "Kenneth",
                             "last_name": "Reyes",
                             "middle_name": "Hanaka"},
                "password": "khr123",
                "username": "ken.han"},
               {"branch_id": 3,
                "fullname": {"first_name": "Dulce",
                             "last_name": "Hugnatan",
                             "middle_name": "Desiderio"},
                "is_manager": "1",
                "password": "ddh123",
                "username": "dulce.pogi"},
               {"branch_id": 3,
                "fullname": {"first_name": "Ollem",
                             "last_name": "Martinez",
                             "middle_name": "Reyes"},
                "is_server": "1",
                "password": "orm123",
                "username": "ollem.john"},
               {"branch_id": 3,
                "fullname": {"first_name": "Anthony",
                             "last_name": "Pineda",
                             "middle_name": "Crisostomo"},
                "is_it": "1",
                "password": "acp123",
                "username": "anthony.pineda"},
               {"branch_id": 3,
                "fullname": {"first_name": "Ralphey",
                             "last_name": "Yumul",
                             "middle_name": "Santos"},
                "password": "rsy123",
                "username": "ralph.yumul"},
               {"branch_id": 3,
                "fullname": {"first_name": "Bon",
                             "last_name": "Castro",
                             "middle_name": "Trinidad"},
                "password": "btc123",
                "username": "bon.trd"},
               {"branch_id": 3,
                "fullname": {"first_name": "Kent",
                             "last_name": "Suva",
                             "middle_name": "Oliver"},
                "password": "kos123",
                "username": "kent.suva"},
               {"branch_id": 3,
                "fullname": {"first_name": "Dwayne",
                             "last_name": "Trinidad",
                             "middle_name": "Castro"},
                "password": "dct123",
                "username": "dwayne.trindad"},
               {"branch_id": 3,
                "fullname": {"first_name": "Shantelle",
                             "last_name": "Suva",
                             "middle_name": "Elise"},
                "password": "ses123",
                "username": "shantelle.elise"},
               {"branch_id": 4,
                "fullname": {"first_name": "Soc",
                             "last_name": "Fernando",
                             "middle_name": "Elizer"},
                "is_manager": "1",
                "password": "sef123",
                "username": "soc.elizer"},
               {"branch_id": 4,
                "fullname": {"first_name": "Carl",
                             "last_name": "Tamayo",
                             "middle_name": "Quiroz"},
                "is_server": "1",
                "password": "cqt123",
                "username": "carl.tamayo"},
               {"branch_id": 4,
                "fullname": {"first_name": "Kiefer",
                             "last_name": "Ravesa",
                             "middle_name": "Bondoc"},
                "is_it": "1",
                "password": "kbr123",
                "username": "kiefer.bdc"},
               {"branch_id": 4,
                "fullname": {"first_name": "Kevin",
                             "last_name": "Muldong",
                             "middle_name": "Umas"},
                "password": "kum123",
                "username": "kevin.mdg"},
               {"branch_id": 4,
                "fullname": {"first_name": "Bryan",
                             "last_name": "Sese",
                             "middle_name": "Balajadia"},
                "password": "bbs123",
                "username": "bryan.ss"},
               {"branch_id": 4,
                "fullname": {"first_name": "Elper",
                             "last_name": "Cruz",
                             "middle_name": "Baninang"},
                "password": "ebc123",
                "username": "elper.cruz"},
               {"branch_id": 4,
                "fullname": {"first_name": "Brendon",
                             "last_name": "Gringo",
                             "middle_name": "Labador"},
                "password": "blg123",
                "username": "brendon.gringo"},
               {"branch_id": 4,
                "fullname": {"first_name": "Rhealyn",
                             "last_name": "Abutal",
                             "middle_name": "Garcia"},
                "password": "rga123",
                "username": "eya.garci"},
               {"branch_id": 5,
                "fullname": {"first_name": "Cathrina",
                             "last_name": "Ganalili",
                             "middle_name": "Bondoc"},
                "is_manager": "1",
                "password": "cbg123",
                "username": "cathrina.bon"},
               {"branch_id": 5,
                "fullname": {"first_name": "Fernan",
                             "last_name": "Galang",
                             "middle_name": "Donaire"},
                "is_server": "1",
                "password": "fdg123",
                "username": "fernan.don"},
               {"branch_id": 5,
                "fullname": {"first_name": "Christian",
                             "last_name": "Pineda",
                             "middle_name": "Manicdao"},
                "is_it": "1",
                "password": "cmp123",
                "username": "chri.man"},
               {"branch_id": 5,
                "fullname": {"first_name": "Paulo",
                             "last_name": "Magnan",
                             "middle_name": "Hernandez"},
                "password": "phm123",
                "username": "paulo.mag"},
               {"branch_id": 5,
                "fullname": {"first_name": "Greg",
                             "last_name": "Honario",
                             "middle_name": "Sanchez"},
                "password": "gsh123",
                "username": "greg.hon"},
               {"branch_id": 5,
                "fullname": {"first_name": "Paula",
                             "last_name": "Garcia",
                             "middle_name": "Ladoc"},
                "password": "plg123",
                "username": "paula.lad"},
               {"branch_id": 5,
                "fullname": {"first_name": "Brae",
                             "last_name": "Trinidad",
                             "middle_name": "Lukas"},
                "password": "blt123",
                "username": "brae.luka"},
               {"branch_id": 5,
                "fullname": {"first_name": "Kevin",
                             "last_name": "Romero",
                             "middle_name": "Alas"},
                "password": "kar123",
                "username": "kevin.al"},
               {"branch_id": 6,
                "fullname": {"first_name": "Kyle",
                             "last_name": "Mercado",
                             "middle_name": "Bulanadi"},
                "is_manager": "1",
                "password": "kbm123",
                "username": "kyle.mer"},
               {"branch_id": 6,
                "fullname": {"first_name": "Jan",
                             "last_name": "Bernardo",
                             "middle_name": "Reyes"},
                "is_server": "1",
                "password": "jrb123",
                "username": "jan.reyes"},
               {"branch_id": 6,
                "fullname": {"first_name": "Janine",
                             "last_name": "Miranda",
                             "middle_name": "Chaco"},
                "is_it": "1",
                "password": "jcm123",
                "username": "janine.miranda"},
               {"branch_id": 6,
                "fullname": {"first_name": "Paul",
                             "last_name": "Intal",
                             "middle_name": "Reyes"},
                "password": "pri123",
                "username": "paul.intal"},
               {"branch_id": 6,
                "fullname": {"first_name": "Ace",
                             "last_name": "Mungcal",
                             "middle_name": "Joshua"},
                "password": "ajm123",
                "username": "ace.mungcal"},
               {"branch_id": 6,
                "fullname": {"first_name": "Mark",
                             "last_name": "Gomez",
                             "middle_name": "Mark"},
                "password": "Lucio",
                "username": "lucio"},
               {"branch_id": 6,
                "fullname": {"first_name": "Zoey",
                             "last_name": "Cornejo",
                             "middle_name": "Malabanan"},
                "password": "zmc123",
                "username": "zoey.cornejo"},
               {"branch_id": 6,
                "fullname": {"first_name": "Chona",
                             "last_name": "Elardo",
                             "middle_name": "Garcia"},
                "password": "cge123",
                "username": "chona.elardo"},
               {"branch_id": 7,
                "fullname": {"first_name": "Elpe",
                             "last_name": "Cabigo",
                             "middle_name": "Gustavo"},
                "is_manager": "1",
                "password": "agb123",
                "username": "athena.cabigon"},
               {"branch_id": 7,
                "fullname": {"first_name": "Donna",
                             "last_name": "reyes",
                             "middle_name": "Bonifacio"},
                "is_server": "1",
                "password": "dbr123",
                "username": "donna.reyes"},
               {"branch_id": 7,
                "fullname": {"first_name": "Derick",
                             "last_name": "Macapagal",
                             "middle_name": "Trinidad"},
                "is_it": "1",
                "password": "dtm123",
                "username": "derick.macapagal"},
               {"branch_id": 7,
                "fullname": {"first_name": "Athena",
                             "last_name": "Lulu",
                             "middle_name": "Mercado"},
                "password": "aml123",
                "username": "athena.lulu"},
               {"branch_id": 7,
                "fullname": {"first_name": "Belle",
                             "last_name": "Aquino",
                             "middle_name": "Manio"},
                "password": "bma123",
                "username": "belle.aquino"},
               {"branch_id": 7,
                "fullname": {"first_name": "Anika",
                             "last_name": "Severino",
                             "middle_name": "Santiago"},
                "password": "ass123",
                "username": "anika.severino"},
               {"branch_id": 7,
                "fullname": {"first_name": "Darlene",
                             "last_name": "Mercado",
                             "middle_name": "Garcia"},
                "password": "dgm123",
                "username": "darlene.mercado"},
               {"branch_id": 7,
                "fullname": {"first_name": "Arman",
                             "last_name": "Reyes",
                             "middle_name": "Lumbang"},
                "password": "alr123",
                "username": "arman.reyes"},
               {"branch_id": 8,
                "fullname": {"first_name": "Anton",
                             "last_name": "Lumbang",
                             "middle_name": "Reyes"},
                "is_manager": "1",
                "password": "arl123",
                "username": "anton.lumbang"},
               {"branch_id": 8,
                "fullname": {"first_name": "Samuel",
                             "last_name": "Muldong",
                             "middle_name": "Reyes"},
                "is_server": "1",
                "password": "srm123",
                "username": "samuel.muldong"},
               {"branch_id": 8,
                "fullname": {"first_name": "Jasper",
                             "last_name": "Kabigting",
                             "middle_name": "Reyes"},
                "is_it": "1",
                "password": "jrb123",
                "username": "jasper.kabigting"},
               {"branch_id": 8,
                "fullname": {"first_name": "Guel",
                             "last_name": "Cabigon",
                             "middle_name": "Gustavo"},
                "password": "ggc123",
                "username": "guel.gustavo"},
               {"branch_id": 8,
                "fullname": {"first_name": "reyes",
                             "last_name": "Reyes",
                             "middle_name": "Annie"},
                "password": "Cabigon",
                "username": "annie"},
               {"branch_id": 8,
                "fullname": {"first_name": "Roxie",
                             "last_name": "Lim",
                             "middle_name": "Garcia"},
                "password": "rgl123",
                "username": "roxie.lim"},
               {"branch_id": 8,
                "fullname": {"first_name": "Chaterine",
                             "last_name": "Miranda",
                             "middle_name": "Bengco"},
                "password": "cbm123",
                "username": "chaterine.miranda"},
               {"branch_id": 8,
                "fullname": {"first_name": "Angelica",
                             "last_name": "Bondoc",
                             "middle_name": "Sese"},
                "password": "asb123",
                "username": "angelica.bondoc"},
               {"branch_id": 9,
                "fullname": {"first_name": "Chriselle",
                             "last_name": "Bengco",
                             "middle_name": "Bondoc"},
                "is_manager": "1",
                "password": "cbb123",
                "username": "chriselle.bengco"},
               {"branch_id": 9,
                "fullname": {"first_name": "Luna",
                             "last_name": "Oroca",
                             "middle_name": "Salac"},
                "is_server": "1",
                "password": "lso123",
                "username": "luna.oroca"},
               {"branch_id": 9,
                "fullname": {"first_name": "Antonio",
                             "last_name": "Cataluna",
                             "middle_name": "Miranda"},
                "is_it": "1",
                "password": "amc123",
                "username": "antonio.cataluna"},
               {"branch_id": 9,
                "fullname": {"first_name": "Albert",
                             "last_name": "Miclat",
                             "middle_name": "Garcia"},
                "password": "agm123",
                "username": "albert.miclat"},
               {"branch_id": 9,
                "fullname": {"first_name": "Edgar",
                             "last_name": "Lulu",
                             "middle_name": "Reyes"},
                "password": "erl123",
                "username": "edgar.lulu"},
               {"branch_id": 9,
                "fullname": {"first_name": "Aries",
                             "last_name": "Catacutan",
                             "middle_name": "Dela cruz"},
                "password": "adc123",
                "username": "aries.catacutan"},
               {"branch_id": 9,
                "fullname": {"first_name": "Nancy",
                             "last_name": "Miranda",
                             "middle_name": "Landrino"},
                "password": "nlm123",
                "username": "nancy.Miranda"},
               {"branch_id": 9,
                "fullname": {"first_name": "Honey",
                             "last_name": "Mesina",
                             "middle_name": "Salac"},
                "password": "hsm123",
                "username": "honey.mesina"},
               {"branch_id": 10,
                "fullname": {"first_name": "Pearl",
                             "last_name": "Abutal",
                             "middle_name": "Mesina"},
                "is_manager": "1",
                "password": "pmb123",
                "username": "pearl.abutal"},
               {"branch_id": 10,
                "fullname": {"first_name": "Jan",
                             "last_name": "Basilio",
                             "middle_name": "Dizon"},
                "is_server": "1",
                "password": "jdb123",
                "username": "jan.basilio"},
               {"branch_id": 10,
                "fullname": {"first_name": "Irish",
                             "last_name": "Basilio",
                             "middle_name": "Dizon"},
                "is_it": "1",
                "password": "idb123",
                "username": "irish.basilio"},
               {"branch_id": 10,
                "fullname": {"first_name": "Elpe",
                             "last_name": "Cabigon",
                             "middle_name": "Gustavo"},
                "password": "egc123",
                "username": "elpe.gustavo"},
               {"branch_id": 10,
                "fullname": {"first_name": "Danzel",
                             "last_name": "Baes",
                             "middle_name": "Salac"},
                "password": "dsb123",
                "username": "danzel.baes"},
               {"branch_id": 10,
                "fullname": {"first_name": "Nathan",
                             "last_name": "Arayo",
                             "middle_name": "Cruz"},
                "password": "nca123",
                "username": "nathan.aroyo"},
               {"branch_id": 10,
                "fullname": {"first_name": "Kelvin",
                             "last_name": "Morales",
                             "middle_name": "Pusung"},
                "password": "kpm123",
                "username": "kelvin.morales"},
               {"branch_id": 10,
                "fullname": {"first_name": "Monica",
                             "last_name": "Tagle",
                             "middle_name": "Magtalas"},
                "password": "mmt123",
                "username": "monica.tagle"},
               {"branch_id": 11,
                "fullname": {"first_name": "Jessa",
                             "last_name": "Dizon",
                             "middle_name": "Santiago"},
                "is_manager": "1",
                "password": "jsd123",
                "username": "jessa.dizon"},
               {"branch_id": 11,
                "fullname": {"first_name": "Jessica",
                             "last_name": "Gahasan",
                             "middle_name": "Due"},
                "is_server": "1",
                "password": "jdg123",
                "username": "jessica.gahasan"},
               {"branch_id": 11,
                "fullname": {"first_name": "Kylie",
                             "last_name": "Due",
                             "middle_name": "Miranda"},
                "is_it": "1",
                "password": "kdc123",
                "username": "kylie.cruz"},
               {"branch_id": 11,
                "fullname": {"first_name": "Chloe",
                             "last_name": "Montemayor",
                             "middle_name": "Reyes"},
                "password": "crm123",
                "username": "chloe.montemayor"},
               {"branch_id": 11,
                "fullname": {"first_name": "Jereena",
                             "last_name": "Miranda",
                             "middle_name": "Reyes"},
                "password": "jrm123",
                "username": "jereena.mirandar"},
               {"branch_id": 11,
                "fullname": {"first_name": "Kristelle",
                             "last_name": "Magcalas",
                             "middle_name": "Reyes"},
                "password": "krm123",
                "username": "krystelle.magcalas"},
               {"branch_id": 11,
                "fullname": {"first_name": "Dina",
                             "last_name": "Reyes",
                             "middle_name": "Garcia"},
                "password": "dgr123",
                "username": "dina.reyes"},
               {"branch_id": 11,
                "fullname": {"first_name": "kabigting",
                             "last_name": "Garcia",
                             "middle_name": "Jalmaani"},
                "password": "Kabigting",
                "username": "jalmaani"},
               {"branch_id": 12,
                "fullname": {"first_name": "Dhaye",
                             "last_name": "Montenegro",
                             "middle_name": "Mercado"},
                "is_manager": "1",
                "password": "dmm123",
                "username": "dhaye.montenegro"},
               {"branch_id": 12,
                "fullname": {"first_name": "Alrick",
                             "last_name": "Nucup",
                             "middle_name": "Parungao"},
                "is_server": "1",
                "password": "apn123",
                "username": "alrick.nucup"},
               {"branch_id": 12,
                "fullname": {"first_name": "Edison",
                             "last_name": "Mungcal",
                             "middle_name": "Falcon"},
                "is_it": "1",
                "password": "efm123",
                "username": "edison.mungcal"},
               {"branch_id": 12,
                "fullname": {"first_name": "Gerald",
                             "last_name": "Sunga",
                             "middle_name": "Simbulan"},
                "password": "gss123",
                "username": "gerald.sunga"},
               {"branch_id": 12,
                "fullname": {"first_name": "Jen",
                             "last_name": "Salac",
                             "middle_name": "Pitero"},
                "password": "jps123",
                "username": "jen.salac"},
               {"branch_id": 12,
                "fullname": {"first_name": "Addriano",
                             "last_name": "Yabut",
                             "middle_name": "Gabondoc"},
                "password": "agy123",
                "username": "addriano.yabut"},
               {"branch_id": 12,
                "fullname": {"first_name": "Louie",
                             "last_name": "Reyes",
                             "middle_name": "Garcia"},
                "password": "lgr123",
                "username": "louie.reyes"},
               {"branch_id": 12,
                "fullname": {"first_name": "Greg",
                             "last_name": "Cruz",
                             "middle_name": "Labano"},
                "password": "glc123",
                "username": "greg.lab"},
               {"branch_id": 13,
                "fullname": {"first_name": "Honco",
                             "last_name": "Dreno",
                             "middle_name": "Labrusca"},
                "is_manager": "1",
                "password": "hld123",
                "username": "honcho.dr"},
               {"branch_id": 13,
                "fullname": {"first_name": "Artchie",
                             "last_name": "Santos",
                             "middle_name": "Kodo"},
                "is_server": "1",
                "password": "aks123",
                "username": "artchie.kodo"},
               {"branch_id": 13,
                "fullname": {"first_name": "Jonah",
                             "last_name": "Martin",
                             "middle_name": "Gutierez"},
                "is_it": "1",
                "password": "jgm123",
                "username": "jon.gtz"},
               {"branch_id": 13,
                "fullname": {"first_name": "brando",
                             "last_name": "mercado",
                             "middle_name": "lipa"},
                "password": "blm123",
                "username": "brando.lipa"},
               {"branch_id": 13,
                "fullname": {"first_name": "Homer",
                             "last_name": "Suva",
                             "middle_name": "Salvador"},
                "password": "hss123",
                "username": "homer.suva"},
               {"branch_id": 13,
                "fullname": {"first_name": "Daryl",
                             "last_name": "Ruiz",
                             "middle_name": "Borja"},
                "password": "dbr123",
                "username": "daryl.borja"}]
        }';

        $data = json_decode($data, true)["json_file"];

        foreach($data as $user){
            $role = Role::all()->where("branch_id", "=", $user["branch_id"])->skip(1)->first();
            

            if(isset($user["is_manager"])){ 
                $role = Role::all()->where("branch_id", "=", $user["branch_id"])->where("name", "=", "Manager")->first();
            }else if(isset($user["is_server"])){
                $role = Role::all()->where("branch_id", "=", $user["branch_id"])->where("name", "=", "Server")->first();
            }else if(isset($user["is_it"])){
                $role = Role::all()->where("branch_id", "=", $user["branch_id"])->where("name", "=", "IT")->first();
            }
            

            $user1 = User::create([
                "username" => $user["username"],
                "password" => Hash::make($user["password"]),
                "is_admin" => false
            ]);
            $user1->profile()->save(
                new Profile([
                    "first_name" => $user["fullname"]["first_name"],
                    "last_name" =>  $user["fullname"]["last_name"],
                    "middle_name" => $user["fullname"]["middle_name"],
                    "user_id" => $user1->id,
                    "role_id" => $role->id,
                    "branch_id" => $user["branch_id"],
                    "is_sync" => true
                ])
            );

            if(!isset($user["is_manager"]) && !isset($user["is_server"]) && !isset($user["is_it"]))
                $user1->profile->services()->attach([1,2,3,4,5,6]);
        }



        

        
    }
}
